# Generated by Django 6.0.6 on 2026-06-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('assigned_tickets', models.PositiveIntegerField(default=0)),
                ('resolved_tickets', models.PositiveIntegerField(default=0)),
                ('reopened_tickets', models.PositiveIntegerField(default=0)),
                ('escalated_tickets', models.PositiveIntegerField(default=0)),
                ('average_resolution_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_first_response', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sla_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('satisfaction_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Statistique agent',
                'verbose_name_plural': 'Statistiques agents',
                'db_table': 'agent_statistics',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('file', models.FileField(max_length=500, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
