# Generated by Django 6.0.6 on 2026-06-30 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstatistics',
            name='agent',
            field=models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(db_column='generated_by', on_delete=django.db.models.deletion.PROTECT, related_name='reports_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agentstatistics',
            index=models.Index(fields=['agent', 'period_start', 'period_end'], name='agent_stati_agent_i_76c175_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentstatistics',
            constraint=models.UniqueConstraint(fields=('agent', 'period_start', 'period_end'), name='unique_agent_statistics_period'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', 'generated_at'], name='reports_generat_cca54f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_report__ff8b25_idx'),
        ),
    ]
