# Generated by Django 6.0.6 on 2026-06-30 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, db_column='ticket_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tickets.ticket'),
        ),
    ]
