# Generated by Django 6.0.6 on 2026-06-30 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='channel',
            field=models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.PROTECT, related_name='history', to='notifications.notificationchannel'),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='notification',
            field=models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(db_column='notification_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.notificationtype'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['status'], name='notificatio_status_a0c93b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['notification'], name='notificatio_notific_fc0984_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['channel'], name='notificatio_channel_717e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['created_at'], name='notificatio_created_307e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_134aa2_idx'),
        ),
    ]
