# Generated by Django 6.0.6 on 2026-07-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='in_app_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
