# Generated by Django 6.0.6 on 2026-08-11 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_password_reset_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(blank=True, db_column='target_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
