# Generated by Django 6.0.6 on 2026-06-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_type', models.CharField(choices=[('AUTO', 'Automatique'), ('MANUAL', 'Manuelle')], max_length=10)),
                ('reason', models.TextField()),
                ('escalation_date', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Escalade',
                'verbose_name_plural': 'Escalades',
                'db_table': 'escalations',
                'ordering': ['-escalation_date'],
            },
        ),
    ]
