# Generated by Django 6.0.6 on 2026-06-30 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escalation', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='escalated_by',
            field=models.ForeignKey(blank=True, db_column='escalated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalation',
            name='supervisor',
            field=models.ForeignKey(db_column='supervisor_id', on_delete=django.db.models.deletion.PROTECT, related_name='escalations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalation',
            name='ticket',
            field=models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['ticket'], name='escalations_ticket__89d39a_idx'),
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['supervisor', 'resolved'], name='escalations_supervi_d09eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['escalation_date'], name='escalations_escalat_025932_idx'),
        ),
    ]
