# Generated by Django 6.0.6 on 2026-06-30 20:04

import django.core.validators
import tickets.models.ticket_attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('WEB', 'Portail Web'), ('EMAIL', 'Email (IMAP)'), ('PHONE', 'Téléphone'), ('API', 'API')], max_length=20)),
                ('current_status', models.CharField(choices=[('OPEN', 'Ouvert'), ('ASSIGNED', 'Affecté'), ('IN_PROGRESS', 'En cours'), ('WAITING', 'En attente'), ('ESCALATED', 'Escaladé'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clôturé'), ('REOPENED', 'Réouvert')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Basse')], max_length=20)),
                ('ai_priority', models.CharField(blank=True, choices=[('CRITICAL', 'Critique'), ('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Basse')], max_length=20, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('taken_in_charge_at', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField()),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_count', models.PositiveIntegerField(default=0)),
                ('is_sla_respected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Affectation de ticket',
                'verbose_name_plural': 'Affectations de tickets',
                'db_table': 'ticket_assignments',
                'ordering': ['-assignment_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=tickets.models.ticket_attachment.ticket_attachment_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'db_table': 'ticket_attachments',
            },
        ),
        migrations.CreateModel(
            name='TicketRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Évaluation de ticket',
                'verbose_name_plural': 'Évaluations de tickets',
                'db_table': 'ticket_ratings',
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('OPEN', 'Ouvert'), ('ASSIGNED', 'Affecté'), ('IN_PROGRESS', 'En cours'), ('WAITING', 'En attente'), ('ESCALATED', 'Escaladé'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clôturé'), ('REOPENED', 'Réouvert')], max_length=20)),
                ('new_status', models.CharField(choices=[('OPEN', 'Ouvert'), ('ASSIGNED', 'Affecté'), ('IN_PROGRESS', 'En cours'), ('WAITING', 'En attente'), ('ESCALATED', 'Escaladé'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clôturé'), ('REOPENED', 'Réouvert')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'db_table': 'ticket_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
