# Generated by Django 6.0.6 on 2026-06-30 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sla', '0002_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, db_column='assigned_agent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_rule',
            field=models.ForeignKey(db_column='sla_rule_id', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='sla.slarule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_column='supervisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_supervised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='assigned_by',
            field=models.ForeignKey(db_column='assigned_by', on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='assigned_from',
            field=models.ForeignKey(blank=True, db_column='assigned_from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='assigned_to',
            field=models.ForeignKey(db_column='assigned_to', on_delete=django.db.models.deletion.PROTECT, related_name='assignments_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='ticket',
            field=models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='uploaded_by',
            field=models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, related_name='ticket_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketrating',
            name='agent',
            field=models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.PROTECT, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketrating',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketrating',
            name='ticket',
            field=models.OneToOneField(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticketstatushistory',
            name='changed_by',
            field=models.ForeignKey(db_column='changed_by', on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketstatushistory',
            name='ticket',
            field=models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['current_status'], name='tickets_current_2bf7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_priorit_668695_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_agent', 'current_status'], name='tickets_assigne_d7ac61_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sla_deadline'], name='tickets_sla_dea_9c882d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['client'], name='tickets_client__2a2053_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketassignment',
            index=models.Index(fields=['ticket', 'assignment_date'], name='ticket_assi_ticket__e6f82f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketassignment',
            index=models.Index(fields=['assigned_to'], name='ticket_assi_assigne_45a6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketassignment',
            index=models.Index(fields=['assigned_by'], name='ticket_assi_assigne_a55618_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket'], name='ticket_atta_ticket__9c179d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['uploaded_by'], name='ticket_atta_uploade_7b271d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrating',
            index=models.Index(fields=['agent'], name='ticket_rati_agent_i_dc1906_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrating',
            index=models.Index(fields=['rating'], name='ticket_rati_rating_7aa112_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketrating',
            index=models.Index(fields=['created_at'], name='ticket_rati_created_2e4d94_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketstatushistory',
            index=models.Index(fields=['ticket', 'changed_at'], name='ticket_stat_ticket__77c279_idx'),
        ),
    ]
