# Generated by Django 6.0.6 on 2026-07-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critique'), ('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Basse')], max_length=20, null=True),
        ),
    ]
