# Generated by Django 6.0.6 on 2026-08-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
