# Generated by Django 6.0.6 on 2026-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_sla_warning_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_relecture_requise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_seuil_calibre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_source',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
