# Generated by Django 6.0.6 on 2026-08-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ajout_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ai_justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ai_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='module',
            field=models.CharField(blank=True, choices=[('Import / Export de données', 'Import / Export de données'), ('API & Intégrations', 'API & Intégrations'), ('Synchronisation', 'Synchronisation'), ('Authentification & SSO', 'Authentification & SSO'), ('Gestion des utilisateurs & Droits', 'Gestion des utilisateurs & Droits'), ('Stockage & Fichiers', 'Stockage & Fichiers'), ('Base de données', 'Base de données'), ('Module de sécurité', 'Module de sécurité'), ('Paiement & Facturation', 'Paiement & Facturation'), ('Moteur de recherche', 'Moteur de recherche'), ('Moteur de workflow', 'Moteur de workflow'), ('Tableau de bord & Reporting', 'Tableau de bord & Reporting'), ('Application mobile', 'Application mobile'), ('Interface utilisateur', 'Interface utilisateur'), ('Notifications & E-mails', 'Notifications & E-mails')], max_length=50, null=True),
        ),
    ]
