# Generated by Django 6.0.6 on 2026-06-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMAPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(help_text='Mot de passe chiffré.', max_length=255)),
                ('encryption', models.CharField(choices=[('TLS', 'TLS'), ('SSL', 'SSL')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration IMAP',
                'verbose_name_plural': 'Configurations IMAP',
                'db_table': 'imap_configuration',
            },
        ),
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(help_text='Mot de passe chiffré.', max_length=255)),
                ('encryption', models.CharField(choices=[('TLS', 'TLS'), ('SSL', 'SSL')], max_length=10)),
                ('from_email', models.EmailField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration SMTP',
                'verbose_name_plural': 'Configurations SMTP',
                'db_table': 'smtp_configuration',
            },
        ),
    ]
