# Generated by Django 6.0.6 on 2026-06-30 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_start', models.DateTimeField()),
                ('sla_end', models.DateTimeField()),
                ('warning_sent', models.BooleanField(default=False)),
                ('exceeded', models.BooleanField(default=False)),
                ('exceeded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historique SLA',
                'verbose_name_plural': 'Historiques SLA',
                'db_table': 'sla_history',
                'ordering': ['-sla_start'],
            },
        ),
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Basse')], max_length=20, unique=True)),
                ('resolution_hours', models.PositiveIntegerField(help_text='Délai maximal de résolution en heures.', validators=[django.core.validators.MinValueValidator(1)])),
                ('warning_percentage', models.PositiveSmallIntegerField(default=80, help_text="Pourcentage du délai déclenchant l'alerte préventive.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Règle SLA',
                'verbose_name_plural': 'Règles SLA',
                'db_table': 'sla_rules',
                'ordering': ['resolution_hours'],
            },
        ),
    ]
