# Generated by Django 6.0.6 on 2026-06-30 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sla', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slahistory',
            name='ticket',
            field=models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, related_name='sla_history', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='slahistory',
            index=models.Index(fields=['ticket'], name='sla_history_ticket__0d8ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='slahistory',
            index=models.Index(fields=['exceeded'], name='sla_history_exceede_f8a6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='slahistory',
            index=models.Index(fields=['warning_sent'], name='sla_history_warning_1b8bca_idx'),
        ),
        migrations.AddIndex(
            model_name='slahistory',
            index=models.Index(fields=['sla_end'], name='sla_history_sla_end_61fb2b_idx'),
        ),
    ]
