# Generated by Django 6.0.6 on 2026-07-23 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slarule',
            options={'ordering': ['plan', 'resolution_hours'], 'verbose_name': 'Règle SLA', 'verbose_name_plural': 'Règles SLA'},
        ),
        migrations.AddField(
            model_name='slarule',
            name='diagnostic_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Temps de diagnostic cible (heures). Vide = 'selon planning'.", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='slarule',
            name='plan',
            field=models.CharField(choices=[('ESSENTIEL', 'Essentiel'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='ESSENTIEL', max_length=20),
        ),
        migrations.AddField(
            model_name='slarule',
            name='response_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temps de réponse maximum (heures).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='priority',
            field=models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Haute'), ('MEDIUM', 'Moyenne'), ('LOW', 'Basse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='resolution_hours',
            field=models.DecimalField(decimal_places=2, help_text='Délai de correction max (heures). Sert au calcul du sla_deadline.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='warning_percentage',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='slarule',
            unique_together={('plan', 'priority')},
        ),
    ]
