# Generated by Django 6.0.6 on 2026-07-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0003_add_plan_and_delay_fields'),
    ]

    operations = [
    ]
