# Generated by Django 6.0.6 on 2026-07-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('ESSENTIEL', 'Essentiel'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='ESSENTIEL', max_length=20),
        ),
    ]
